version: '3.8'
services:
  back:
    build:
      context: ./back/
      target: production
      network: host
    command: pm2-runtime dist/index.js
    ports:
      - "5000:5000"
    networks:
      - dockerlan
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  dockerlan:
    driver: bridge
